// Current active tab state
let currentTab = 'international';

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    updateIntLabel();
    updateLabel();
});

// Tab switching logic
function switchTab(tabName) {
    currentTab = tabName;
    
    // Update buttons
    document.getElementById('tab-btn-domestic').classList.remove('active');
    document.getElementById('tab-btn-international').classList.remove('active');
    document.getElementById(`tab-btn-${tabName}`).classList.add('active');

    // Update form sections
    document.getElementById('form-domestic').style.display = tabName === 'domestic' ? 'block' : 'none';
    document.getElementById('form-international').style.display = tabName === 'international' ? 'block' : 'none';

    // Update label previews
    const domesticPreview = document.getElementById('labelPreview-domestic');
    const intPreview = document.getElementById('labelPreview-international');

    if (tabName === 'domestic') {
        domesticPreview.style.display = 'flex';
        domesticPreview.classList.add('active-label');
        intPreview.style.display = 'none';
        intPreview.classList.remove('active-label');
        updateLabel();
    } else {
        intPreview.style.display = 'flex';
        intPreview.classList.add('active-label');
        domesticPreview.style.display = 'none';
        domesticPreview.classList.remove('active-label');
        updateIntLabel();
    }
}

// Print active label (6x4 inch)
function printLabel() {
    window.print();
}

// Update DOMESTIC label
function updateLabel() {
    const senderName = document.getElementById('senderName').value;
    const senderAddress = document.getElementById('senderAddress').value;
    const senderMobile = document.getElementById('senderMobile').value;

    const recipientName = document.getElementById('recipientName').value;
    const recipientCompany = document.getElementById('recipientCompany').value;
    const recipientAddress = document.getElementById('recipientAddress').value;
    const recipientPhone = document.getElementById('recipientPhone').value;
    const barcodeValue = document.getElementById('barcodeValue').value;

    // Update Sender Details
    document.getElementById('lblSenderName').textContent = senderName;
    document.getElementById('lblSenderAddress').innerHTML = senderAddress.replace(/\n/g, '<br>');
    document.getElementById('lblSenderMobile').textContent = senderMobile;

    const rowSenderMobile = document.getElementById('rowSenderMobile');
    const divSenderMobile = document.getElementById('divSenderMobile');
    if (rowSenderMobile) rowSenderMobile.style.display = senderMobile.trim() ? 'flex' : 'none';
    if (divSenderMobile) divSenderMobile.style.display = senderMobile.trim() ? 'block' : 'none';

    // Update Recipient Details
    document.getElementById('lblRecipientName').textContent = recipientName;
    document.getElementById('lblRecipientCompany').textContent = recipientCompany;
    document.getElementById('lblRecipientAddress').innerHTML = recipientAddress.replace(/\n/g, '<br>');
    document.getElementById('lblRecipientPhone').textContent = recipientPhone;

    const rowRecipientPhone = document.getElementById('rowRecipientPhone');
    const divRecipientPhone = document.getElementById('divRecipientPhone');
    if (rowRecipientPhone) rowRecipientPhone.style.display = recipientPhone.trim() ? 'flex' : 'none';
    if (divRecipientPhone) divRecipientPhone.style.display = recipientPhone.trim() ? 'block' : 'none';

    // Generate Barcode
    try {
        JsBarcode("#barcode-domestic", barcodeValue || "AWB123456789IN", {
            format: "CODE128",
            lineColor: "#000",
            width: 2,
            height: 60,
            displayValue: false
        });
    } catch (e) {
        console.error("Domestic barcode generation failed:", e);
    }
}

// Toggle IOSS field visibility in form & label
function toggleIossField() {
    const chk = document.getElementById('chkIncludeIoss');
    const group = document.getElementById('groupIntIoss');
    if (group && chk) {
        group.style.display = chk.checked ? 'block' : 'none';
    }
    updateIntLabel();
}

// Toggle VAT field visibility in form & label
function toggleVatField() {
    const chk = document.getElementById('chkIncludeVat');
    const group = document.getElementById('groupIntVat');
    if (group && chk) {
        group.style.display = chk.checked ? 'block' : 'none';
    }
    updateIntLabel();
}

// Update INTERNATIONAL label
function updateIntLabel() {
    // Sender
    document.getElementById('lblIntSenderName').textContent = document.getElementById('intSenderName').value;
    document.getElementById('lblIntSenderSub').textContent = document.getElementById('intSenderSub').value;
    document.getElementById('lblIntSenderAddress').innerHTML = document.getElementById('intSenderAddress').value.replace(/\n/g, '<br>');
    
    const intSenderPhoneVal = document.getElementById('intSenderPhone').value;
    document.getElementById('lblIntSenderPhone').textContent = intSenderPhoneVal;
    const rowIntSenderPhone = document.getElementById('rowIntSenderPhone');
    if (rowIntSenderPhone) {
        rowIntSenderPhone.style.display = intSenderPhoneVal.trim() ? 'block' : 'none';
    }

    // Recipient
    document.getElementById('lblIntRecipientName').textContent = document.getElementById('intRecipientName').value;
    document.getElementById('lblIntRecipientAddress').innerHTML = document.getElementById('intRecipientAddress').value.replace(/\n/g, '<br>');
    
    const intRecipientMobileVal = document.getElementById('intRecipientMobile').value;
    document.getElementById('lblIntRecipientMobile').textContent = intRecipientMobileVal;
    const rowIntRecipientMobile = document.getElementById('rowIntRecipientMobile');
    if (rowIntRecipientMobile) {
        rowIntRecipientMobile.style.display = intRecipientMobileVal.trim() ? 'block' : 'none';
    }

    const intRecipientEmailVal = document.getElementById('intRecipientEmail').value;
    document.getElementById('lblIntRecipientEmail').textContent = intRecipientEmailVal;
    const rowIntRecipientEmail = document.getElementById('rowIntRecipientEmail');
    if (rowIntRecipientEmail) {
        rowIntRecipientEmail.style.display = intRecipientEmailVal.trim() ? 'block' : 'none';
    }

    // Product
    document.getElementById('lblIntProdDesc').innerHTML = document.getElementById('intProdDesc').value.replace(/\n/g, '<br>');
    document.getElementById('lblIntProdQty').textContent = document.getElementById('intProdQty').value;
    document.getElementById('lblIntProdUnit').textContent = document.getElementById('intProdUnit').value;
    document.getElementById('lblIntProdTotal').textContent = document.getElementById('intProdTotal').value;
    document.getElementById('lblIntProdOrigin').textContent = 'INDIA';

    // Customs
    const chkIoss = document.getElementById('chkIncludeIoss');
    const chkVat = document.getElementById('chkIncludeVat');
    const tdIntIoss = document.getElementById('tdIntIoss');
    const tdIntVat = document.getElementById('tdIntVat');

    if (tdIntIoss && chkIoss) {
        tdIntIoss.style.display = chkIoss.checked ? 'table-cell' : 'none';
    }
    if (tdIntVat && chkVat) {
        tdIntVat.style.display = chkVat.checked ? 'table-cell' : 'none';
    }

    document.getElementById('lblIntIoss').textContent = document.getElementById('intIoss').value;
    document.getElementById('lblIntVatMsg').innerHTML = document.getElementById('intVatMsg').value.replace(/\n/g, '<br>');
    document.getElementById('lblIntCurrency').textContent = document.getElementById('intCurrency').value;
    document.getElementById('lblIntWeight').textContent = document.getElementById('intWeight').value;

    // Order No
    const orderNo = document.getElementById('intOrderNo').value;
    document.getElementById('lblIntOrderNo').textContent = orderNo;

    // Barcode
    const barcodeValue = document.getElementById('intBarcodeValue').value;
    try {
        JsBarcode("#barcode-international", barcodeValue || orderNo || "4100569160", {
            format: "CODE128",
            lineColor: "#000",
            width: 2,
            height: 50,
            displayValue: false
        });
    } catch (e) {
        console.error("International barcode generation failed:", e);
    }
}

// Download the currently active label as an image
function downloadImage() {
    const labelId = currentTab === 'domestic' ? 'labelPreview-domestic' : 'labelPreview-international';
    const labelElement = document.getElementById(labelId);
    
    // Ensure styles are correct
    labelElement.style.transform = 'none';

    html2canvas(labelElement, {
        scale: 2, // Higher scale for better quality
        useCORS: true,
        backgroundColor: '#ffffff'
    }).then(canvas => {
        const imgData = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.download = `india-post-${currentTab}-label-${new Date().getTime()}.png`;
        link.href = imgData;
        link.click();
    });
}

// Official Base64 Template for India Post PBE / DNK Bulk Upload
const INDIA_POST_TEMPLATE_BASE64 = "UEsDBBQABgAIAAAAIQDfz5sukgEAAJQGAAATANwBW0NvbnRlbnRfVHlwZXNdLnhtbCCi2AEooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzFXJTsMwEL0j8Q+Rr6hxKRJCqCkHliMgtXyAsaeNVce2PFNo/55JSitAIQjSA5dEWfw2P9vjq3XlshdIaIMvxGk+FBl4HYz1i0I8ze4GFyJDUt4oFzwUYgMoribHR+PZJgJmPNpjIUqieCkl6hIqhXmI4PnLPKRKET+mhYxKL9UC5Gg4PJc6eAJPA6oxxGR8A3O1cpTdrvn1Vsmz9SK73v5XUxVCxeisVsRC5Ys3X0gGYT63GkzQq4qhc4wJlMESgCqXx2SZMU2BiI2hkJPxA5tO1kD2qBLdq4oZ5NpJYgewvZ7m7KGXiAbspEb5nhBp4wB7U332uwXdMbfEm8Dh76y9T2DOI5s5wNJG7GDozq47k9eQls8hLA+dSt2GvFLW73S3lYAr9JhCRMmF6y0A6kYbMIPIkJDIwj6zNm4uYO29qS3K5jbqreFzNfb4XRm06Dj7Jzr6r8q/5aGV09cld+fAOexxf5gPLFUCMyXeyRYH3y4+Ynfp2K8NHRL8PojdHlKPblkRsjlTJm8AAAD//wMAUEsDBBQABgAIAAAAIQC1VTAj9QAAAEwCAAALAM4BX3JlbHMvLnJlbHMgosoBKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMks9OwzAMxu9IvEPk++puSAihpbtMSLshVB7AJO4ftY2jJED39oQDgkpj29H2588/W97u5mlUHxxiL07DuihBsTNie9dqeK2fVg+gYiJnaRTHGo4cYVfd3mxfeKSUm2LX+6iyi4saupT8I2I0HU8UC/HscqWRMFHKYWjRkxmoZdyU5T2Gvx5QLTzVwWoIB3sHqj76PPmytzRNb3gv5n1il06MQJ4TO8t25UNmC6nP26iaQstJgxXznNMRyfsiYwOeJtpcT/T/tjhxIkuJ0Ejg8zzfinNA6+uBLp9oqfi9zjzip4ThTWT4YcHFD1RfAAAA//8DAFBLAwQUAAYACAAAACEA9PUHOxsBAABZBAAAGgAIAXhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvJTPSsQwEMbvgu8Q5m7TdnUV2XQPirBXXR8gpNOmbJuUTPzTtzcUSS0s9VL2EpgZ8n2/TDLZ7b+7ln2io8YaAVmSAkOjbNmYWsD78eXmARh5aUrZWoMCBiTYF9dXu1dspQ+bSDc9saBiSID2vn/knJTGTlJiezShUlnXSR9CV/NeqpOskedpuuXurwYUM012KAW4Q7kBdhz64Py/tq2qRuGzVR8dGn/Ggn9ZdyKN6IOodDV6ATFFfKxskkAM/DzM/ZowSrbqScvGTDAxtQSRrwkRjz9BxNRvR/IlmOzCMNkSzHZNGNLSYfnmXRgFmrozSy/B3K0K44c2TF58tTTGS/a3a9r7MM84uY8hH9d4H3z2IRQ/AAAA//8DAFBLAwQUAAYACAAAACEAPNWmZJwCAADbBQAADwAAAHhsL3dvcmtib29rLnhtbJxUbW+bMBD+Pmn/gVn7SnkJ5AWFVCGAVqntqjRrt0+TA6ZYBTuyTZNq6n/fGZKWrNMU7YvJne+ee567c6bnu7oynoiQlLMQOWc2MgjLeE7ZQ4i+rVJzjAypMMtxxRkJ0TOR6Hz28cN0y8XjmvNHAwCYDFGp1CawLJmVpMbyjG8Ig5uCixorMMWDJTeC4FyWhKi6slzbHlo1pgx1CIE4BYMXBc1IzLOmJkx1IIJUWAF9WdKNRLNpQSty1yky8GZzjWvgvauQUWGpkpwqkofIA5NvyZtjhAzRbKKGVvrWt31kzV5F3ggwtNo7Srbyza9NY3dPWc63ITIdF9r3fGxu28t7mqsyRK499CCk830h9KFU0HTH1k6F10utI0T+aIgMnCn6RFZ4DQGaitUr3/YQaLRfg7UC50LRrCIxUZhWEoam+3wBWhwQFlD4IS7yFqmfddusbyjJYKhvCW4vwdWl+wkXrBsp9LuXMuilDFq2bQ5QzElBGcn1EI6tPe0Fb5gSzwueA4dZD/3T56+f3UAf3nhq9WCOMI9RdJU/QK41CBzvQPqQwCzDVXYjDP1pm+Z6vjPRSshOXUq139Gd47/b0ppmgkteqLOM11a3oO923bEtx+nWvYU0GkFD9Mvx7PnInnimnQx80xtPXHPsDVxz4cVu4o+SOIn8F1hpqBscHpxmWWKhVgJnj/BMl6SIsIQV79YE+PYrRP44sgeA66VOanrOxDajaOiZfpwO/JETLxI/fTk8wZ2WX/ynwrHVZhOsGqFnOe3QAu1N995XZ9E59uM7amGwjHXf99n/CrwF9RU5MTi9OzFwcX21ujox9jJZ/bxPTw2eX0Xx/PT4+XI5/7FKvh9KWH9tqNUOXJ+wpvA3cViT2W8AAAD//wMAUEsDBBQABgAIAAAAIQAK/xeaeQcAAM8gAAATAAAAeGwvdGhlbWUvdGhlbWUxLnhtbOxZzY8bNRS/I/E/WHNP8zWTj1VTlM8u7W5bNWkRR2/iZNz1zES2s9uoqoTKiQsSEiAuSNw4IAQSSCAu/DGVWvHxR/DsmUzsxGmzqz0A2u2hGc/vPT+/9/x7b+yb7z2NGDojXNAkbnnlGyUPkXicTGg8a3mPRoNCw0NC4niCWRKTlrckwnvv1rvv3MQHMiQRQSAfiwPc8kIp5wfFohjDMBY3kjmJ4d004RGW8MhnxQnH56A3YsVKqVQrRpjGHopxBGrvT6d0TFClVK6iAvxXqaCRUu/dWk3UZ/AYS6EGxowP1TRkp7SWm5yWFVosRZdxdIZZy4P5J8n5iDyVHmJYSHjR8kr6zyveulnEB5kQkztkDbmB/svkMoHJaUXPyWcn+aS+H/i1dq5fA5jcxvXr/Vq/luvTADwew6pTW2yd9UrXz7AGKP3p0N2r96plC2/or27Z3A7UPwuvQal+fws/GHTBixZeg1J8sIUPOs1Oz9avQSm+toWvl9o9v27p16CQ0fh0C10KatXuarU5ZJqwQye8GfiDeiVTvkZBNuSZpqaYJrHcJ+8i/CThAwArIYYljZFczskUjyHTu5jRE07REZ2FUk2JDwg23qdDY7E1pGZHYszpXLa8O3MMe2et9dWvv7588fPLF7+8/Pjjly9+MLVbcoc4nplyf3372d9ff4T+/Ombvz7/Ip16Ey9M/OvvP3n92+9vUg8byzDryx9f//zjq68+/eO7zx3a2xyfmPARjYhA98g5ephEsEDtHdsecsIvJjEKMbUkcAi6Har7MrSA95aYuXAdYrvwMQdOcQFvL55Ytg5DvpDUMfPdMLKAx0nCOgl3OuCumsvw8GgRz9yT84WJe4jxmWvuLo6tAPcXcyBW6lLZDYll5gOGY4lnJCYSqXfJKSGO1X1IqeXXYzrmiUimEn1IUQdTp0tG9MRKpLXQIY0gLkuXgRBqyzfHj1EnYa5V98iZjYRtgZnD+BFhlhtv44XEkUvlCEfMdPgRlqHLyOGSj01cX0iI9IywBPUnRAiXzH0O6zWCfhc4xB32Y7aMbCSX9NSl8wgniYnsJafdEEdzF3ZI49DEvi9OIUUxepBIF/w4sXeIeoY44HhnuB9TYoX77UTwCOjTNGmdIOrNgjtieZskVv4Ol2yKiYtl2jyy2LXNqTM7OouZldpHhDB8jieEoEfvOyzoJHPL52uj74TAKofElVh3sJ2r6jkmgiDdxWxT5BEVVsoOySzZYc/xcoN4ljiOMN+l+R5E3fR5H+qYk0rvs/GpCbxHoQmEfHE65b4AHUZy79T6IMRW7VLPwp2vS27Fb589BvvyiWXGHvsSZMiFZYDYTZk3+maEmTXBOmFGGFoIF92CiBX+tYiqq1ps4ZSb2pt2HQZog6yOJqLxW9ubNPmvvrFxbKqraWncii1SenWxZmYXaRxutDC7cP/BxqWHF/EDArVim5Wu+5brvsX73/ctu/bydbeyq6e47lY86CKuu5XsdORqupV1gwK9izo/SE9t9BlOtNcRzpQyNpRLRo6EPsUR8P0yGcCg0qGPOEl+vDcP4acqeTCZhZtxrGUQT+QHVIbDEM/hBKjsKSUzkameCTRPBJxC6mGnboVni+g4maSnmOWyOrFMq6zAcj1eCvJxOHWSKbpWX5/M5eq1tTN9mroyQMlexAhjMtuIqsOI+mpQOUmf3YLTHEbolV2JFU2HFQ2lfhWqLSvAtDwq8IGN4LO85QU+iIAQHL1BMz5RcUpDvYquDuZVRnqXM60MKMERepYB60g3la07l6dWl6baHpG2jDDSzTZCe0Y3eyKEz94sO9XoPmZcNNbNdUgt85QrMl8YZtQbb7LisrEGuU1uYLHJFCxG5y2vVg0gZcZ43vKmcAIMP6M55I5Q31iYzeCqZSx5uuEvwyxzLmQPizB1uCadlA0iKglHjEYtTy0/DwOLNYdo28oVIIR/rXFNoJV/m3EQdDvIZDolY2mG3RhRnk4fgeFTrnC+1eKXByvJZAHhHoaTc3TCFvwhhhQL6mXlwAkVcE1QTr05oXDLlRPZOv82ClNGu+Y1k86hdByzeYizimKSeQrXVJ6bo59yHxhP2ZrBoYZLskJ4MlMF1nSqVU3zqpHasLPqvl1Iec4gzXXNtFhFVU03i1kzrMrAhi8vV+QNq1YuhnJpVviUujcpt7niuo0+Ia8S4PDcf46qu0dBMExbT2aZpizepmHF2dmoXTtWC3yLafsUCYP1ayu1G37La4RzOhi8VOUHuc2shaHpqsfUntbX5ObtdXLyBMijBx3vgkmhQwn30RxDQzTUPUlKG7BFnspsa8AvtOC05T0rBW2/Wwm6hVIj6Bf8ql8qNIJ2tdAOgmq5H5RLvU7lORQWGUblIL2iH8CFBVumF/Utz8tu7DVg69Y+Wl3O3BgnUTHRt/JFvQJ9a1+u7Hdrjygw0bNaZdCsNju1QrPaHhT8XqdRaHZrnUKv1q33Br1u0GgOnnvoTIP9drXr1/qNQq3c7Rb8WkmtqdEs1P1Kpe3X242+336e9TbgjpRTMgeBz7WNt/4BAAD//wMAUEsDBBQABgAIAAAAIQA7bTJLwQAAAEIBAAAjAAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDIueG1sLnJlbHOEj8GKwjAURfcD/kN4e5PWhQxDUzciuFXnA2L62gbbl5D3FP17sxxlwOXlcM/lNpv7PKkbZg6RLNS6AoXkYxdosPB72i2/QbE46twUCS08kGHTLr6aA05OSonHkFgVC7GFUST9GMN+xNmxjgmpkD7m2UmJeTDJ+Ysb0Kyqam3yXwe0L0617yzkfVeDOj1SWf7sjn0fPG6jv85I8s+ESTmQYD6iSDnIRe3ygGJB63f2nmt9DgSmbczL8/YJAAD//wMAUEsDBBQABgAIAAAAIQDdpxymrwcAAMYgAAAYAAAAeGwvd29ya3NoZWV0cy9zaGVldDIueG1snJptk6JGEMffpyrfgVD3VgXEB6xdr1aBE58Vk7xmFXepqBjA3b1c5bunhwGd6aZS7t1Wyfiz6Zn5dzMw9D18/TgelLcwSaP49KjqdU1VwtM23kWnl0f1941b66pKmgWnXXCIT+Gj+j1M1a/9X395eI+Tv9LXMMwU8HBKH9XXLDv3Go10+xoeg7Qen8MT/LKPk2OQwdfkpZGekzDY5ScdDw1D09qNYxCdVO6hl9zjI97vo21ox9vLMTxl3EkSHoIMxp++RudU7T/sIviNTUhJwv2j+qT3NrqpNvoPedd/ROF7KrSVLHj2w0O4zcIdKKAqWXyehvtsGB4OcHJHVdhUn+P4L3amBzYa9JHmZ7A+gm0WvYXc2mNq/Z33Ck3osXHtUmyX3bu5OMtE2YX74HLI1vH7KIxeXjMYR4udvo0PYAufyjFi4VGVY/CRH9+jXfYKrW7dNFqdrm60VOU5TDM3YieryvaSZvHxz8Kq8MW9GIUXOBZeLBbj7wcIrw7NO900CzdwLAfTrrc6WjMfi+Dvf4ZiFj7gWPowhAnd5wRmnqsCx9JJs66bWptpcp+LduECjqULaN4pBGRI3j/LlELvZr3bapntbuf+qEDm5F7gWHoxBSnuHAuEL/cCx8KLYd6CcqcTHRaB3AtrlIPRPz8l/Zqv0CiH8xMJq5cZyxqln069o2tW8xMK62XGssbNjdFt6a08V+6Vp8xaWFRKP03tmnH3einTFq700ove+XzE9TJ3WaOc1U/EvMxi/ZbGRvsnYl7msS4l8qcvB7YQ8RwUUrn7WZGNMpNZoxBHt+4WucHX33wNt4Ms6D8k8bsC9ynI5/QcsLue3gPXsEQz+sTwowrZBWswuxG99c3WQ+MNlv5tYTIoTOBws2nLNsMqm45sY1fZdGUbp8Km05RtXG4Dn7fhWLLJN2rS0mSTUdGT6MVENh61aVmm7GdcdAWZfB1Oy0LjmVQYtTXU27QwEhy1NV3ubVZlY8g28yobpOGiygbNbFllg3JjVWWDcmNdZYNyw6+yQbmxqbK5Cd2APL8mOyy6VcnOMOR/J89zJO2A/2i0+UVgGpoFf7K0Q27ThJFcg93WkZFdaYR6c65G7JJDP7oGHwPOkG+cG13U44hzvYmT3OO9sPXxOl7U15ibCNPWLQ3+yROfFI7yhzK2bkxLcHNsGrdg5GvL7A6b+R02iztslqUNewJlA1xhsMbAx2AjACmbYHWsyiaG2bpadjngAKQsyZATyJeS2IQ4hHicQNTKs8aETApyNZliMMNgjsECgyUGKwzWGPgYbAQgiQgPHlUiMpxfkuVcB5yIKnIiqkiIQ4jHiagiIZOC3FTEYIbBHIMFBksMVhisMfAx2AhAUpFtDyru4gxLqciBKCInooiEOIR4nIgiEjIpyE1EDGYYzDFYYLDEYIXBGgMfg40AJBHhXl0lIsOSiBwIkg0JsQlxCHE5uS0C3zAYYeBhMMZggsEUgxkGcwwWGCwxWGGwxsDHYCMASXW4CVWpzrCkOgei6oTYhDiEuJwIqmMwwsDDYIzBBIMpBjMM5hgsMFhisMJgjYGPwUYAkuqwpalSnWFJdQ5E1QmxCXEIcTkRVMdghEH+AkocyxhbTDCYYjDDYI7BAoMlBisM1hj4GGwEIKkOG8Aq1RkWZzrgQFSdEJsQhxCXE0F1DEYYeBiMMZhgMMVghsEcgwUGSwxWGKwx8DHYCEBSnb37qZI955LuBRGFp8imyKHILZAgPiEjQjxCxoRMCJkSMiNkTsiCkCUhK0LWhPiEbEQih4Jt1ioeVNj7NfkSKIgUCm4kIJtaORS5xPs3QkaEeISMCZkQMiVkRsickAUhS0JWhKwJ8QnZiEQOBdvWVIVC2O7kW6YBe1cJwRF0H1JkU+RQ5BZIvCpwfyNi4xEyJmRCyJSQGSFzQhaELAlZEbImxCdkIxI5FGxzVBUKYdNUhIITKRQE2eytsBwwhyK3QGIocH8jYuMRMiZkQsiUkBkhc0IWhCwJWRGyJsQnZCMSORRsh1UVCmHnVYSCEykUBNnsxToOBUFuYSWGghvdyIjYeISMCZkQMiVkRsickAUhS0JWhKwJ8Qlh9czr0s9DwSuN/C31OXgJZ0HyEp1S5QClTChZ1uGZNuGlxbwNRc6cwrbuOc6gVFh+e4USbQjvfLQ65PU+jrPyC7xTYH79MLuclXNwDhM/+gdKhvAAEScRFGPzGuyjeo6TLAmiTGVl5SzaBgf7HIE/6L8X7R7VxNvlAQo/smlaVI97H9AjKiAfo20Sp/E+q2/jY4PXfUkJWTcbSfgWsWIvvOYDl8olgc5+DIdO+6nV6tSszmBYM5+7Vu3JHrRrtjW0msOnp0HTdv8tC88fuvlzvWtWw+Il7P4DOOntoEbwR3CI4MjK0co2vpxAfLgD5zXy3geofM8sw49tKBbIq7wr2fczqH+IUlA6fY3fvdP5ks3CNIUg5X0y6CRJnIjwI+ldWBR+GEO31dT0Yc1wraea6VpObdDU2jWnbQ6sDpQu4Sr8FzRl82JF/Msh0OHbsbfveyde1Yc5/vZl/cXowQe8p85/gwM+IS+I9229B8+AZrfV4aaccnNZNyiXVIgJFMLLPyFvoHH9Hwj9/wAAAP//AwBQSwMEFAAGAAgAAAAhAPSgU2utEwAAomwAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0My54bWycXdlyG8kRfHeE/4GB57WIvnAoJDlW164OE2sd9jOXgiSGSYImIMn+e3fP1ZnVyA3JLwI1OVPV1V3Z3VOTAzz463+ur06+bu/2l7ubhzN3bz472d5c7D5c3nx6OHv/7vlfVrOT/eH85sP51e5m+3D23+1+9tdHf/7Tg2+7u3/tP2+3h5Ns4Wb/cPb5cLi9f3q6v/i8vT7f39vdbm8y8nF3d31+yP+9+3S6v73bnn/oLrq+OvXz+eL0+vzyZtZbuH/3PTZ2Hz9eXmyf7i6+XG9vDr2Ru+3V+SG3f//58nY/e/Tgw2XGSkAnd9uPD2c/u/vvfVzNTh896Hz/43L7bQ9/nxx2t6+3Hw9PtldXD2ev3OykxPb7bvevcuaLDw9n82x0v73aXhQvJ+f54+u2P/udS7l//t35KX9nH6eTE/x7dPi864/f7k4+bD+ef7k6vNl9+3V7+enzIXd+d/nF7iqfm/89ub4sIzI7uT7/T/f57fLD4XP+a3HPxfnCZ8e/b/eH55fl0tnJxZf9YXf9z+Gc0pDJhh9s5M/BxureKqW4WC2/30gYjOTPwYif30vLeXA/0JI4GMmfg5Hw40Zym7suyZ+DkTII39kXi+Hi/DmGke5Fn5arH4ljOVjJn4OVxQ/3RSZWF0b+HMOY/3hL1oOV/Dla8T+aHy6Tvk+y/MdoJUJb/iC33JSghTd99oUFXPud4+LG1Ch/DHZ8hDT9ozaMGVHyYGz/euqFP7pyTAdX86H8+b2NHvPA1UTw7v8IfswFR8nwgzR3Yy6UP8YudNCFfxzVaT/zdLPX0/PD+aMHd7tvJ3lSzgO7vz0vU7y77/N/ylwVU54SLwr6c4G7k/LhMvt+fZTcg9OvefK7GE553J+SB7ae4vmUJ0esBD7laXtK9OacZ/05OQ2qp8hmnrenRLfmc37pz8mJUM0kPuXXI6cs+JQXR05Z8ikv+1Ny9kyOTFPKcpS7N8+60xnLORt53Rpx5pSzfMp0ffSmoRtGTRt/680XblUTwTj4+5GTbK++ITcrDuItgcGkxztE09o4f987p+Fa1xhPcx5PyZzXQEzmMYnL4Yez/G8Nkdv3uD+jb8fvXZqbLH+CZwxEMEE+bU+J3uTnM2zEwmTdcwSjN/3wS2+e+4HD+LU9xXT1C3Rh6PXS94GbyF/hJWllgn6N6MKk9xmCSxPthkDTT78hGL2x+3dETXPfIBaDifEto6ZJ7xBNa9N37xmtRKIUzFw+loLlMKeg8f24PwNT0CTAEzyjT8GFCf5pe0re/XCSPMvnTDxYVCJ18/1zBKM35n/pzWMKLkwnvUADC9P7L0OXYcGYfYXXxGjQM0SXtde79m4INMG8QTDfkHA/vEU0BnPtO0TT2gTyntHKCUqFvCQeS4VymFNhYbL/cX+K6/b5ZRl+Yg88ywfqIJpOeY5g9HaEEF2YTnkZ+xEy17zCa9LK0PEM0aUBNwTWnuqG7w2C3k4fbxGNoUZJvZxXriO9/LgcLhuXcqvUdaE98LJscr4+Wpt0e4Ur4cK09wzBlblyQ6Dp2DcIxmAG/C2j1StFmnl3JNKfy2GM9LE98MQeeLnoQ1+bsXqVT5yyKkaTBGeIrgwjNgSaK98g6FdmQnqLaAy1TRR83kUdC74cpuDtgSf2wFk+MAVp27IhsI4SNSVv44805SwfrnZrsvbzFIF1riG7eWN/zG4+XO3W3untEijyptwBHjNcjk+WLQ82jNZ0piaXG8Sjpvt1rF+l7Oy5KVdVxzVZ2HRebo+axmV4bXJp4wgVA+jy9H3UNE7rS0vvctXUatUfeco6ahmnsrVNjnJXPFlWe9uyRT9qGucOy+gNbezXKkEyA4+aRma6edMhDKsuKQQc7jDj/dyeYUI+K7fVU9RubicUA6ssATKydWScmzd5wrBKFKAkW0feuXkzoAwLvnvgJVkvAPSM5byBxaCWm/mj/V6Aat3ZUTWwGFUP7OS2IwGds6NargPnYlQ9EJStIweds6NargPrYlQ9kJStIw+ds6NargPralSBp2wdiers/fOmFFrBuhpVoCpbJzLanfvGM6xGVXHVI1djbEYVYQc7TprRveJqAabQY6zD1q9xBDuoCrF1xVVPZLS3QxsDV+dkPSiuFmBqu/M2ZwwsciYorhZgsh6jzXeCnRc5ExRXCwDWa+P6fifYwU0494ziaiAy2pu+jYFFRgbF1QJA25t+R9hBxYnbrrgaiIx2u74xcKUDW1dcDURGe+u5MXAddLauuBqIjKEmxTCqDNeOY+uKqwG5mmvYfFO9YVht5oPiagFgVJu2I+ygUkBtj4qrBQDrdl0l2MHtD1tXXI3E1WR7hmAHUyhbV1yNyFXXzAQGFrNYVFwtwNQzLtak6HPGwHWi4LYrrkYkY7QPEDYEu1gHna0rruanFbXty7qjGJqOqIt1zNm4omokqrZNZ7iOOVtXVI3ExVTnkaHtDNfQ2Lqian4qXjsmpnr5YB1hl1TKKKpG5GJs246wS2ISS4qqBZgSMkLj+rYT7JJIyKSoWoDJuks14wbrDFc2UL8nRdUCVOu2xLZhOImMTIqqBQDrdlQNXHf33HZF1YRUdbYwuTFwTVi2rqiakIwRkmLod4QdPB5h64qrCckYISkG6wg7qHyzdcXVRGS0lcGNgVXOKK4mIqN9CLhhGAql3HbF1URkbOZIA4ucWSiuFmDKyJhq6H2/E+yWImcWiqsFAOuWqwS7pZjFFoqrBZisu2WdSIa2MyxmsYXiagHAetN2hmvH0aguFFcLMFmPMJEMbUfYQV2erSuuLpCMsZnFCHYrsfItFFcLMLXdrewsZmCVkYqrC+LqqibF0DMMq4xUXF0QV1dNzjCsckZxdYFcjfYJ34ZgtxI5s1RcLcDU79E+vdsQ7OBhL+XMUnG1AJN1Z5/kbxiGx0hsXXF1SWS0j2c3BhY5s1RcLQC03eaMgUXOLBVXCzBZj/bB6IZgB1Vt7hnF1aL0A+tN2xF2qsC8VFwtAFivCd2ziWAHxW1uu+LqksjYFLANXKdQtq64ukQy+qaEbWAxiy0VVwsw9YxvStgGrpMctX2luFoAsG773cB10Nm64uoKueqbEraB6yTH1hVXV8hVP6+b3D5nDCxGdaW4WoDaM00J28BiVFeKqwUA65XqQ9sZVqOquLpCMvqmhG1gNaqKqyvkqm9K2AZWo6q4ukKu+qaEbWA1qoqrK+JqU8I2sBpVxdUVcRWqyMOoMixGda24WoCaM02R2cBiVNeKqwWYrEe4denbTrAHASBxda24WoDJuocq8mCdYbHjWCuuFqBat9LCDcOqyLxWXC0AWK/DNrSdYbEnWCuuFmCyHhc19ME6wh60Ztzviqtr4mqw87uBVc4orq6Jq6CeGdrOsJgJ1oqrBZh6xkOdd7DOsJgJ1oqrBajWoc47WGdYzARursjaIWDfzvAWr1lFA5ufiItHrB0CDuzQWlyMrZsrynbI5CC/62HK8Iz7KIY3P3WXERBtoSjbD0F35dQADxVj00WKuG5O1GzK5QZXhdv8ZF9GQOxsyp/dlTUCKO2aCBR93Zz429QoLV6zzDhQDM66AqRBU9CyeM0y40CR2M2Jpk0d1OJ1/jMOFI/dnJjaFBEMDiUMdoAKJnrq7Uil5Jv7WYuLBcChjsk4wKXXNwXR7sqaRXBjZyKQTCbFkm/WdmdwNcioaTIREJPbqYJ0TR4WOROBZDLJl3xTu3SMq+JlVnMoJpOIyTfly+7KOgYg3DIRSCaXt4LAQJ2Oh8nO4IrJRbJ0VHKTtSTkoE7HowPG5SBLJpd3iyCCZj0wuGJyeblIREBMhnrfGAHhqtropOapQ2oETUXQ4orJUvbkSNjkm6KgxdUgS+VT1r3gGDR1QYurQZbipyx9IQfNIBtcDbLUPzlSOPmmfmdwVcDr3rU8nkUkcvJNCa+7siYBaFKZyUXNJBwQk9cNk0kH5UGZahxIJpMSykMtbeCBweUgSyaT2smDZHN0QExX5bYs15FdhEwN9rWIrKBF3ENBjrtIKqIcaZ7CvO6ehwgMrpgsRVGOZE9h3gyywRWTpS4q64WAaBFWrDECxAOIS00Xyd01iZ9CU3xzBq/rhXEg12SSR4Wm/uYMXqcS40CuySSBCk0Jzhlc3aMVrdNxJpMKKjRCUmfwmmUmAslk0kmFphDnDF6zzDiQTCYtVHB1EMcsQibLnaPUSjkSSwVXx3C0j0QOUAvkAKRcKqu7gAbBvpC4MTiUA40DeZtMmqgAutEhAoOrmaKIn44nEcmign0bM0dARIaioIlAEpmUUQFKb2MEuGQHqAsaB5LIJI4KTXHOGVyt+UUkJboIb5NDU5/LUjNKglrJNxFIIpOEKoAUc+wiXLID6ESNA0lkUlGFRqyZ5WwYgSrTZeGZ7CIkamj0mt2V064lQCHPRCCXZNJShUaymWVrFIEaZKmmcqSXCo1q0+BQzuMIpKDKkaIqtveAhAeo6BkHksmkmopwjzdkEeFBiTedlFV1SB3ERoRucbWpKAqp40Qj7VSAktwYQb4SGqB2jkVDJRwQU9uSHamvgizZFRmVcEBMbUt2JMAKsmRXpFLCATI1tjf6JLIKsmRX1FLCATG5ES1mKSCOAdQMTZpKJpOUKjQKN2dwtamQWitHaqrQiK0sXjcdHIGUWzkSVAUoyQ1pavC66zAOJJNJchXamiDjU2HbmJcrMmmuQlsRNLjaU0jVVRZFQo5E0LONHYR4kPu6IqA6nqQkrQoggxwdEM+hJGm6SPKY1FUBKn6jA+I5lCSNA8lj0l+F9v7J4DKHJI9JghVB9TdGQDyG5chEIHlMMqvQzkQGV1kkdViOlFahjcDgarmRUixHYqvYfPsG41D65x4qoqrjWUpyq9AoJ53B1XIm9VhZKUo8qzPZMMaEB/hmCBOBXJBJdBWgZDk6ICIvVZYW8ZXoIiJq830BjmRbAWqqJgJJZJJeReiCMQIiMtRUjQNJZFJfReiC0QEu2AG+FMA4kEQmAVY8MgZEZCjaGgeSyKTBCm1R1uAqTaVIK0tfMU1hEIcuIjwowaYreqvjWURKrNhmEeFBaTazxlY6yEjdeLZVXxJrBVn1lWotR3qs0FZ9Da4mUynYcqTYipDn4xgQk2XVt2ivxBggkyPk+egA8QBlZ07TIr8SDpCpEfJ8dIB4UALRrAeWDoipUDYeHTBeZ1sTgWQyybMClI1HB8RkqGsbB5LJJOCKzTd3OMahrs0OpIQr65WBB7GtWxtcpalUcTnSacV2LmIc5KQmAslkUnJFqEsPY2BwdfchtVyO1FoRJrPRAa3Zc5VFUs7lSM8V53XNHR0gkyMUzk0XSSazpMt+ld4ma68pCVS5q4izjjOZZFsRpuMxAmRyhMK5iUAymYRdsS2MG1wVxqW0y5G2K7aFcYPLLJJMJnlXhAVl7KJ85bQgJVWNyt/oJcagQyYDsVnRGE9QDqMxyHJx6QBVIRGeU/YRdFdODYBbXGNfEdkX4dd0fWxWTMaTKqdlRboMgIgKK+IYAOJJldN8EXEdpUGHQAQ1SUYHSOSkXof2Ut7VIeCgbtxGB0jkBPU8MwaKyJ7kXbF50st4gjeyjQNF5Ky5p0GuVd0xAsTzFzofL4X4IuISY4BLboQld3SAeFIFwazelw6QqLFZ87srpzFKUJHkLpLyLk/yrgRr+hAB46ri6KW8q0NqC5v3QwwOJU8TgWQyybdSs6nwjKuSppfyrg6BCGqhYOwiYrIqafoi0jqeRSTfSs3T9u7K2gCoqZouUktyfgcCeJCaXYvBQWdpHEgmk3wrwa5k7CJckhMUbY0DyWSSdyXYlYwOiMkg5DQOJJNJvpWabZFnHKrCxoFkchF+1UFs9AL5XQ/EVbnIS3lXh1QHzb7L4FB25gikvMuTvCvBvmoYA8blmizlXZ7kXcnVfdXoANfsBC9umgjkmkzyrdRs7DzjUNk2DiSTSd6VXLMmM64q176IuI5PFSTvSs3OsbuyJoGqXOc3WKQDYmojqeiuBAd1U2C6SDKZ5FsJNBPjIBOTVWk8v0QjI6A1txFtdFdCBHVTYCKQTCb5VgJRxhgBMRnkwOxAyrs8ybdSowoxOBT/jQO5uSb5VmreA/OMq+K+l/KuDql93MhODA7Pmk0Ekskk30ogKxnGgHF4umAcSCaTfCs1uhbPODyjMg4kk0m+lUC3MkZAazY8vjAOJJNJvpUa4YxnHB5fGAeSySTfSs0Xs3nG4fmFcSCZTPKu1ChzPONQnDcOJJNJ35Xg1bhxDIjJUJxnB1Lf5UnflRrpj8GhOG8cSCaTfiuBtGeIgHGonRsHcndN+q3UaIs841A7Nw4kk0nflUA7NEZAu2uoPBsHksmk30qNeMkzDpVn40AymfRbCcRJYwTEZKg8GweSyaTvSo06Kr98hltHqNsaB5LJpN9KzZuM+eUzcqDuk6W+q/x8FGx+G/mVwaHq2UfQ/yZU/6sqH/Jvq/zj/Ooyf5bfrDq52H25yUuNy996y9DJ4b+3+Re3ri73h7xV+Lz79vRud/t0963/Vahy4MXN7ZfD37b7/fmnfGLhWD747O5ud0cH+5+nyj+D9XP57vbyi1xfrs7do9mbzevXP52c5Y+fTp5unvx08tPswekEPzjl5uQfdOED+WeqbrPjv53ffbrMcVzln9DKP5V1L3f1Xf+DVt3f+ce1uqM5h37fHfJPVI3/+5x/C2ybv7l+fi8T5ONudxj/U35Da/p1sUf/EwAAAP//AwBQSwMEFAAGAAgAAAAhALOFWozCDgAAAEQAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWzMXG1v47gR/l6g/0F1g+IOWMWm3iy5SQ60LO068Vv8stfrN2+sbIy1rdRWNlkU9987lEiJ4mgTK7l2CwQR82g4nBk+Q1KUmLNfnrYb7Wu0P6zj3XmDnLYaWrS7iVfr3efzxmIe6m5DOyTL3Wq5iXfReeNbdGj8cvHnP509xvsvh7soSjTQsDucN+6S5L7TbB5u7qLt8nAa30c7uHMb77fLBP7cf24e7vfRcpVW2m6aRqvlNLfL9a6Raejsj9ER396ub6JefPOwjXZJpmQfbZYJ2H+4W98fGhdnqzXcYw5p++j2vEFJhy6I2WhenKVtf1xHjweprCXx/SC6TfxoswHpPmlozLlPcfyFifZX540WaD1Em+iGNaMt4fI14uLjNgToX1lDUIZGmnkrclm0GKYBmey1VXS7fNgkfrz5db1K7s4b7mmbtDyzbTfEvWn8+CFaf75LoGdspvom3oAe+K1t16y7Gtp2+ZReHzMdxDq1DLvtEgO0HJJvG+gyAmKfokMSrpmehnbzcEjiLW+UcLWZQoMrhCtXaDinhmsT23mdQpMrhKtQ6FYrfMYqiyuB6wtK7tarVZQF5hl9EJo0bHDl+gjrxCxaBvh+ZLQcrgeuwq7WKbFacqxqqAMbUrPgKsxyVHU1+hISN1UHV6HOfhM5PK4Qrs8oZA4/E3sCA0zGWSiIqCE3a0SNRSRTCAVhl6nGrY5CkQSkyALinNrtlilnVR2NIgsgiXMT2zgN6qgU3CMF+QjB3VtHpeAfS4Y8kK/JCyKoxwqij8mpa9uW47LhrX6qEUE+VihUorGuhr+GYCIrCH8rMqSOSsFFQ+Kiix2vkcWs9ZTerCCs9HBH11Ep6GgUozIQHMWSqXwmkw0xLLOCsKxdX40YjdkEI9S8cRYTyWEUyWGYxez6inlR5IZR0I+4aEyo0QmmYB8rCLeNN1HFFOxjBaHybZE0BftYQaj8DlWOnDRNwT5WECrb6nhdJ5KCh+bLPDzWRsFJU+KkUU3tY1UKTpoFJ4lZyaBncs4UPGQFETwbaWEsPdYuMVabxVhdtYisMQqaYqxmhcJINPzX6GNLZAsrCJV4Tq6jUSSLVSSL0XpT/lkiWVhBGAkEqj/cWCJHWEFost6QI5bIEVbgCj1VX40utkSCsALX5+L8qKNR5Icl5cfbeljkilXkSoWNdTgjcoU4plsEUnpuK7qaPQdmT2vp02BvmSwvzvbxowZPucC4w/2SPTOTDhgHD3QMpQyGp8CGBo9p7DH264Vz1vzK9HCJLpZolyV8LOGWJXpYwjIUmSCTYeui3BSvrCasECGtssx73BQhZZEPmQiME3lDxCiLsMdxCAtbq+QytmeXhS6rzDHLMlcVMhZRQjzgQkDrvDWLKFEeVmgiVrm1UZWMYvW4ojHVoEmVHsWe6woZiyidOq0QUmVmVTJKz88rZAyl5xeZjNythtLzHzMR9jiYB9pQuv7XKhmlV/9RIWOZSmO/ZUJyahlKf/2zQo+h9BetSFFDIRCtSFJD6S/K07TsvNJftCJTDaUvKM9U2TFT6QvKU7XUmBogynNV7jFT6Q3Kk7WsSOmOdPeMDWxyv5pKrClP15LZaqx5urLlcU4QUw22SNeSkBptnq4l39Rg83Qtm61Gm+drSchSw80Ttiyk8JHyjC0LqfGuylhLjbdI2dKApcab52ypOdtTLedZq0gVpjdh+srnMFjiyHMYG6LZfkm2ds32ONlEJ+Y2Jp5KsGmtUJlOfN38ZtrTyR5q3V70w59847zReAc/2sfBeHy1mADyTuvvsj1l2In9y8noxOicjE8My32nwb2QDmbBzz+fNW9ZO4tZeUz2oaGcS7aaub2SGREyQrKhygTiue+Md2UD/jpq0rIJQdaIwSLz9UJNwzC/W9jpKCx8b6RVDVfpvg8ZTkxbudHnSmHBUjjvKQlwWdWykm1XXAYWaLkiR533BlWKiJLcw0pNSnOjSiEluceVQopzk0ohJd2uK4WUdJtyIZgs8hBY6qg8qxBSKD/PG0tp4MFsrfTaIpPIXlukafIbIHmjDlFoQWnptjojU5ZkRW11NqaQGuz1QroOZYkgiSpxoozC0m0lQpRzmG39SVLqiAQsTgeE9K1M1mxOYMO0PMcyXYUPlHOUDTOg+VOaBkrUqOAoLPml1hX6UUFSJ9XRdtuuZbVdT+EWBZqmw5X5PYs4RYlVBK/MkMxIpfNpQZBUPWgvDxKU0yPTWxp2YRVcY9jtMvFsYGbRkEZWE42sZp2RtReULfbl1bnRUuIdZGbAoCc4FiLkfcGED0Wxz+WKAF+imlcccXLtAyQzRDIjhIwRMkHINUKmHCl8myFkjmotMkTO7sJpSqUydKEIGoUo5+WeVIb45jiPLKRfDkFoUa5JNUT80neXWSqKABYhpRDBXCGPXYn2yGmK40B5ICp4DZNTHV4z8UpeW4jXVg1eg4f5w7ZfcC7ImpP5i5D3hfiHotjncgVyiWpecaQI9gDJDJHMCCFjhEwQco2QKUck/iJkjmotMkTmb+EipVK5K5WlkNKehEN8c26FXLPMX9QYlUJMRfxk/iKDKUQwb4PHrsRfXqMIA51hiAeigr+w/K7DXyZeyV8b8dd+LX+zDwbYjB5kzcn8Rcj7QvxDUexzuSJ4l6jmFUck/iKZIZIZIWSMkAlCrhEy5UjRcTOEzFGtRYbI/C2cplQqd6WyL5V7Uhnim3Mr5Jpl/qLGqBRiKuIn8xcZTCGCeRs8diX+8hpFGCiOA+WBqOAvrOnr8JeJV/LXQfx1XsnfIGtDJi1C+hyR6IlkrhAyQMgQISOEjBEyQcg1QqYImSFkjpBFhkj0pO8xJDyTqIZdo9yTEllQgxRbRblZFWSBxXUdsjDxSrK0EVnaryVL1oZMFoT0OSKRBclcIWSAkCFCRghJPwqDTesiHSdI5hohU4TMEDJHyCJDSmTBkPBMJgtSRbknJbJgKWwV5WZVkAWeA+uQhYlXksVFZIEtn6qNmMq9IBg785VdkLUhdU6IkD5HJLIgmSuEDBAyRMgIIWOETBByjZApQmYImSNkkSElsmBIeCaTBami3JMSWbAUtopysyrIAnu0dcjCxCvJ4iGyeK8lS9aGTBaE9DkikQXJXCFkgJAhQkYIGSNkgpBrhEwRMkPIHCGLDCmRBUPCM5ksSBXlnpTIgqWwVZSbVUEWtlFdhy2pfCVdSAvxhbReSxjejMwYDPUFJHFGQMWkcYWhAYaGGBphaIyhCYauMTTF0AxDcwwtOFTiTwWWeykzCKujwqkShyrkKqyjwrwqGrE3f9LreDGkfOdVRpfwN4V8G1TaVCME04i8mkZZMyUaIajPjYFP8MTTwaWAZBqhigMsNcTQCENjDE0wdI2hKYZmGJpjaMGhMo14J0i7UleiaolGyHOgEa9bxIxWGEcrrAMayXVLO7NsW7oWjfgOeAWN8GsvUue9V2mtk5pVWomGGOoLqAjJpYBkGmUmS5QcYKkhhkYYGmNogqFrDE0xNMPQHEMLDpVpxDuhRCPuZYlGyHOgEa9bxAxohOUqrAMayXXLNGIbqXVGI765CwqVLX5i4tGoziZ/mUZofzeEQLKhUmJDX0BFSC4FJNMIVRxgqSGGRhgaY2iCoWsMTTE0w9AcQ+wgUTpDSJR5X4FdiaolGiHPgUZcXxEzoBGWq7AOaCTXzWiUHT7KPjdLvzyb7OOEn1vKTjAN4psv0YqdXmJrZzZv3N/B0a5kfQOHkm7jXcIOPMF2UvLtHg4P7WI/3vHzYUx2BR+yfVxu1nBlJ660m/hhB8Qz4U1Z+Ravv1kfkoa23Gzix+5mufvCmtQOd/Fjf3f/kAyjw2H5mZ1RysBgv4/3MhgxYL5O2Dmm/u4ra1gLdsn+GxxTY7fOG5NNtDxEWuabtswM2n/TbvfxVkvuIm21j+9X8eNOW+80OGz1sIXLqTZc7h6WGzjrBrq09UHbxUlmZbRigskdYPD9HkifgmnZ+a4u6XRJy3LtNntxyL5CeNgsyUV/1OtPA3/+U6PX+Ntye//36fjXn9KPEITEWbMcm/9OrLiVvtPxK6z0WUftv42W2wg+j/ijLEMdJowwOrBbKgXp2OaVSMFpt3sgyHC5/7wGtm3gmB6cxjuFPYl9di4uLcMBvhQF1n6KEzjcJv66g/OGEZCkdQqZchtDJvA/gMnRUzI48NOLnSfAlQOM2/XNPj7Et8npTbxtZucO0RFGYjX30dc1O2wI3oJK7WG/Pm/82/cDh9p2W/faXV+3PrmeTntdR+95vmf6lHbNXvi7OPj4RKzXtd7yml52hPLiDJR0yizLk5OtkdNDmp0niMwxbkZPN5F8QrNK/R+T4E/7zsN6BREj8Bmq7YYtvU1bpm751NI90/F04vstr9s2u25g/A4xZn4W9H3aduBTIfmLoC77Iqh7Aq/U03twUSukFL2gU6PDRloNvivowBdp8B0DVMjuZZXK0fwfhMAhdkB84uqkFTq65YVEd+FTY/izF5jEcRw/bB0TgoCFIHg5BOD4/4Xf1IejwKHZ1rutnqtblmPolDqhbrZc6gcu7flucIzfgxOzczJ42e/Q6MDq5cf3d7sLB2vbtqN3XR8GCdINdWo4VO/a7HsUz7c80j3G78kJfKPzPNunpDPlk8KP99u3AyvoWrYe+C3o79AN9G7PcXXDMtphK7QDw3SP8fv6Zb9npAPbAemU/eP9dvyeHwa9tt4z2gHw3DMgv01fb8HY5sNk0Wt1e8f43Wf53X+Z53QEIxssMH+8577r24bVNvQefGmmW72Wpbte19V9r03blhv2eu5RPT5nns9PMo/gG8/vDu5z8ByWxz/ec6NNoYv9UA/bgQdcp77uUjvQDY94gdM1PNM4KscvmeeXJ/BN3POJHhid4O1+H79Az+dvahu+7QW2bptmD7rYdHUYxQzdhv8e4HtAALdrHUPuBXN08TK5+zCtwy7qH5Lar3C36xO75ZimHnZtGLshd3Xa7hI9bBH4cZ2wZ9s13H2R0X0DvH2Zz2lClBcusIRuwsI0+w0rXijk/7vj4j8AAAD//wMAUEsDBBQABgAIAAAAIQBXuXcJiQ4AAN85AAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWyMW1t32zYSft9z9j/g+GGbntPGcdpk227iHt5E0SIphhelzhskIRJiiVBB0q7863cgyW4XH5Ttiy/AABjMfDMYzIDvfv1ju2H3QndSte8vrl6+umCiXailbFfvL5p69P1PF6zrebvkG9WK9xd70V38ev3Pf7zrup7R2LZ7f7Hu+90vl5fdYi22vHupdqKlns9Kb3lP/+rVZbfTgi+7tRD9dnP5+tWrt5dbLtsLtlBD27+/ePuG1h1a+fsgglPL67cX1+86ef2uv/aad5f99btL89+xJcntlnBa2E1FZbeU0zS123JqtNuqqEy8lOVN5kel3RlGVZ3kXp1McxZMm7wub+l3GP0dutzLgC7zElrKq5syYvVt4e6vSy+vimlZO0mK8W2VBMTxxyiJxzVyEqReGYVs5qUNzJ/TPsIoTWYRbSTJq7psArM5kF4V5WFUMi8MWZrkEbuy17EJXv8/gh/OEARJfXuu6yRxlyRP639NKSeSIsldKjv1RkYlSXiGAy+tSd957QUg6NP4yW1gjy2jIDISJkUjAp47g2lW5N7t14nOy/95nmcS0ACSgA6eSVxaeO6saq8GKD33fkoKl3yf+89I+Ln/jHyf+2vvN1vCRi1m36PUi6GvrJMgjc4Y9Elr2dRP0vNbcncXZVR4t1mUuw3zYHBsOmJ/0tm8kcU1ZNyB2/gPvecst5i6t+s36YSV0chayrjrX7odX5AbJ3/cCX0vLq7/x9eZUcwadj2unP6NmskVBmVSGG9hD6oK1uQJWQqaUXFyU6ye1h763oLlUX3Gk1Vjr4iMPL2jRu1V/ek0jTxgxuXe7KEHz5ccPB8ra3B+MwNox5ij7uyO8+ou4Dy539mjK1g9h6XpiLaHjTK7JZyCI/JsGjg2UXpqMWxF29sjvQz4tM+yF6HoFlrueoouvoXxQ9drvpHc7gjWsoVGApTsxfYYMdgjPBvr197n1Zq30oQuQAyY8zZzooUlw08wdLMSGgk9UI/XLpXWMKM3hRnbldogXeKgG+TGQYnOru3lauCXPtfzYYlTAwA9vSLtOkTuAaA8TUBw7P8jsKuHOSxdja+ArluI1sSe0FFDi4GLY21U0qPQcy6/oOZ9AKzP15xiVnstfwwtfK0pYoVm0LzP29WGL0W3BlofWkhFfKlweYh+fLHhekBCOK+IcCWHLawEUiJC+SiA7gZaSOG4bUCGL/TWgTYf1OivB4dN+mAYvtrIe1S3/wEY9KAF4Oirvnvg6FR8MAZf80e5sWecgZX5uU3jI82wWXEHZH3wVj7Yuz/ooV1Ke5EJADPg2zld18DYAlARUQqt0NQCEGBAokLPEcyAG8BpAFurwUKCNV/aMwXgk+kQ2AA8g/QKRoIiAsBSoDZqO0cZTVBGaqs0GmQwgWUBOQHocIw0WvEe+QgamN7hPgOAdTBovuAKBqNa9juH9wjAKWC0FsLOQ9Fuub6zFw3Bc4Rf5FwNPWA4BKmHaitbuQAMh6DJGsKVKLA5iRYDOVUNzWCf0Wq/622yClAef7BpMCkQadlTigMIwT9HXa8cJ2gEfjLq11LtECsjUMgIpDQCXYzkF9DDCAA7ku2GUj32LkaA45Hm7QKsMwbjL6ClhpbYs9eL+Ry9VAyoicnzoXxiEHksKAWFhJixiekM4+0e2AGfG1NoCbqOQZyxnFN823OAYgwCjbUQDoGCVzR0Th3FIbCthcuLx2BBMZmL2KhhhwptYNKBb6ENsEszUqjOMVqNwQbjQei2Eyh0cOvxIFu0sBicYnwLDA57h74wTzbmEr3VGBgZq3ZJjheCsTFY5hjkNx5aCglgt0ll85wsKOJDU8SsVEI3jVZ0iO8EQJaQ1cI64NyI6negAqNKtJs/sNIEMJx0mgsIsRJAUdLzDUjqBha4oQDecXbcAM5v+A73fwM7u6FkOOLxBpzsjdJLnG8CZ+qEP/K7tesiOoG1J6Ldg2OZJLY6JlLLOQUS0A5n10R16h5nBKOZDA8EfpgPzHWy16v9o2szqWePTjkGUilwmPLeEeanPswm6I6Ox0IKlpOKTvVrCIpSMIdUzl2X+fQWlpZz1EoKWkmlkKYG0na9wCtTCvhOZb8eXHmHFNxGOvwhKMwf9MrmLQNcZhQSDkAGvonIBHkO9BsZKD2jy8CKdws8yDIAUkZe/wGAmYFMDd3e4bUyAAhRLuW9AHebgWMhSlwZxE5UPVhEBmd89gFkyDVlSUyNCnoAWxkfKCJ0KTcD5R5pJd7ubx2871Xf4/q/AUfiD7kAG8jkQrsPiyyEGdRm6XAdWYCELXcsBcdmpkyqy4G3yDFjL1qx0rgBsHaatadMtuY9zAIOKaOr3cLBKrjsTD2a2NKlaTh+Moot6D5kr57D6jnfSke8mgN2csLOAPPBcZaLHYdTNAejyEW/FtrEEmBBOegyB1Hk4OZyOmw1pwwjsAiKzCWlS4EM/MuBDIGRNzBUou1NUDDgEnOlH/jenm0KupxS+G9TFeA5C37nzCsX4AwLcnKgSWoUHTkSASsBZAoKW7cg5wIEWIB7LY4qgj1jebkQCLYCvGFB2Ri52xHXgKICLL0AEBaU48ZgtgD/VijdDyuE9QcQzQfuuFcFIJkSMFkKemeAcUQJoCkVoQFRWQIqy+bKVmXZvIYmQEdJGUnMslUoe8BpVsCKFZeO6PYj+MuKbxUgykMyWLMCFVSg+Mp4bdReidNThh5FGyBdYIuxEnsKsTZkQtADqKsADhU9a+E7pcH2KjhBK7D7akPn4R2yXYGLNJSuOknlA9MAu4pg5zglqymq/EDpMqxTRdv11uDUZV4aeDm4jVPvobh/2YB5fmMVSRmVOZ7Ke/bOPArXzc10aXdQcfV7VmipKEAC/2Q6c9We7XdVcr/GRaHomVJJ/pa3GDbRsUCyZqHYCAow8VZ+eIqk93RwA15OXYEiCdgbHEdpEZXBNG0ysJAkDxM0pOPDmtO7FXu6o06+oSJ8U9XTrDrU6PPpZTLFOvGfVfev1eYLsCp8ylJIVz5K8y1sdyI3isXUYzMe0BkEURldehzWVxyfJrlfBMTyM0wzNUFN96KmjEbHF5Jyqh1rVU/VYVKkWLL5ntER2LPkW5srX7VcavEdI1/Qs4iKinSRHjpGaGUVx6Klrzo6BQ7dY6EfxUrdO0qlPoFZdms2k5RqbFnSOQMun2o6QrLQlPI6ig1AZFT1uaPZ2Yh3EPsGfCfYTOglgpHv6ag6t2hAxV1KQzLvs6bIrSVr2A3zjVzYgjkUXFjE6faqT3MBiVJ3Z5chS+OsdGRiAtULtvwmuVckd5jyUSzWZ3kKxVYtCEVy8UzC1GcWmKuEPdNTEeH8Ds3eWC2pwmOPjTak+829s2zwOyUzyVeRBN0ZyBHf3BltnxPMiGslznZSkpb2TzM7MpSjYycFT3tnhu/UX72s6QJENoAe7Mgx8yXBbbA3TXnMFZvQD7uD0CuMmDOMhjOuuzXfbM7tJxcPLKAA15lZMJ2fBOEeQ0Fyxf2amHHUUAq+GzgzY93yL2S/IIs+i/+CMsy9MsgEyDyZwllMlWSnpBk2chxjp64XmeoW6gH8zNPQF1X/khWCjKqjdNMK6ChwIz80pjMISwrHPnLFWouDB8rMnZQe4toaO0R13zGPCrwOA6xoB6Q42YIAKj4sJfM0d0Rj1SFGOy5Ll2z3hbwyvHGWCjrpgSmzsYyTGxbIsKnI0jl/xlFWVDdcnzwWTHvoc0LlOKyidwi44M7xeqMyjS9MtVvvn1hBBWnJUt7eQdRsFEuPbOgk2ojtHtjs2UT2fcf+xbe7/xB+7yUcnWaGdFg4QsqXtdqK7yhKahcS6zJm3Iy6yLOfpq/Xgs5gU/BxXdHcEqEMFV0vUW33nJ5D6eVB8zcH6OwdCnww7yQcllw9iKWLXPb0LMc5YE/O1ZZezdeOWkzNJd2ZkPaLdN/Ia94+uu5w9Zo7eT+cDd9TAhljxVrhiVOT70TOSapyyY/iq9WcO8bpQ/6ALTkLhnaNU9AN1ZEarSk4wMKEaTWPslw5edN3jGwCKpGo7gnjIMGBdA7nQ7Mi9QJzzZ15BwWoaVp6nbc8uBIWbSWd2RgYn2gmdAlbKoh9Tr0VxWOiMx75jDdr9EDJJ7C35mVljOJr4VfzOBduoMx4S6c8SGBmIg+ygMBxU5mRQ3wkZwwCmknRk13ZMv5Ip6Y8KmM09AM6+48GdnSMVfQkTcOst4KUbM/5yVkB/yS3cz5/ABV98uzxk9JuiSpsubKbUrga+3D3nuQwKrBbKrhgzpAmhFHAdAXPHSrIY1aRPU8AiZbq1qYpRrD5GvI4NSxfw/I1LFbjU6Ya8hX11OaoBplV49dABMKvQWh1BqNA+DUUYxpgsQFUeSDq2LfXagBnDQh/lsAokOussWlmwM8M+JmBfD6O7Hki0NgtzPMJZPgJ0EH3ikMwHSuFGfhAbSlkowDA3D+2O3zwVvju7wJMO77wv6ZmEJppg0ZKFEzLJE6+/gkTfcVhvlwYRWVEHyjYEqLe851hCHn50IOmcV017q8LqiIKzDdYRTmNSy+jD5NC+sKpngKOn772oY8Cssh8A5KHrJg2QFeUSeYdPtU6frJF9JUZYO+qiujjk/DvUP5l5cBDXzatx/S9T+AXxPtoWmaHL8bs1Z5yOvTlSmI+o6Adh14NECYphPRVlvM7DNrYtGT5lD5xiYy4zhKWUZzQ111PX67h+6cHgqhoGT1uWlKhkGPWZbew+TffroAI4+bGczR3pghwJxkFwnSFnFMMxrimZMrS/GlP3K3ppdMXzqj0S9EG22m1HBZ9Z5P9+OZnpuVyuZasO/6iD1sk7WKxt0np8ZBmfL5glPPb2J10ypMN0uvMJbvjWy2+2ARzKqOxB7rqY0Hr9dWPP7Grt9TP7wUDFvmuZ+D//KTMkjweO57Yp57vZYCAH968fvXm+zev3l7ZnKXF6zdvfv7p32/eXv31s8hL+kDz+r8AAAD//wMAUEsDBBQABgAIAAAAIQAfvyJhmwQAAFcYAAANAAAAeGwvc3R5bGVzLnhtbNxZ34/iNhB+r9T/Ico7mwQIByvC6Vg2aqXraaXdSn01iQPWOXaaOFto1f+9Y+c3IYHjYO+uvMR27JlvZj6P42H+fhdS7RXHCeHM0a07U9cw87hP2MbRf39xB1NdSwRiPqKcYUff40R/v/j5p3ki9hQ/bzEWGohgiaNvhYjuDSPxtjhEyR2PMIM3AY9DJKAbb4wkijHyE7kopMbQNCdGiAjTF/OAM5FoHk+ZcPR3+cBinvytvSIKuCzdWMw9TnmsCRAPQNQIQyHOZjwgStYxkdMCFBK6z4aHckAhyueFhPFYDhpSZaZ4MU/lrB5dplxxLWXHFMWbtaO78DPhd2tlt/Bg06hru2p6O5cchZqTQz0SIAmhtGTnWLITBhbzCAmBY+ZCR8vbL/sIuMlgq2QcU/NOzN7EaG8N7fMXJJwSX6LYPKgdUZJH0keKWecvCPPxDvuOPhkr6TXAcgOcA+5QV86dL1ajtIEr1zz2IdsUW30EZmRDiznFgQDwMdls5VPwSJrCheAhNHyCNpwhCk2jWFE85UrIUpCQHF1sVULJcgVKBc9ThSEn5dJPzlUYFISTUwFmgfLk3MyYH8KWDo/nrodAepjSZ+nyP4IymkOI5i7QWBq6ofgVeAeniUyzRRMIlzezyGUdUNW1yIL1xxdpKIro/lMarnHsqiNGaVOjckNWvaViXNX/QMmGhVgeNABPLXiKucCeUEegYrZRty6ztWbm6DI7tV1w0mDpsGMGgyOK1Rnkwip1DHa57wJpmfSajyyIKZytmcu0v2IUveAd+E4pNnZBd/CG59riAkWkwC+wbPQNZIM3yxj8mQJjnmIckF2FvLCjh9BduOuyMw7nPumR9dX+fYNYA8bSZw27DmOd9esbURIvKjemRrn3WR5l2f7s4924gxvfAkvXDmxhqfbzFT3Rpb3Ftqv4vUtbT+66oq1dR0WpvZ1frqj9YtsbmfY4oM7se9Hu6MoaLU6ckc3Otjo7kdsR6Mluk45dXMYTlPdmlB7ZXbhbPmh+X5x71oKL6983hxlQfZ30yqrFqCELOn3ZtMvLx2l1EXtqnmsga0cltzLTfevs1sDSimLTL1fJdbUzpqH7fxOhN89LXcxqe/T2zKrlnkZ02yxvfLk2eVZx/rxMBJ+GX5c1ah5syGqjvr0Hu7C8xd6EkAVgobxrNfzQZtJZ0fuesicwSV1N4TJau4E37t/lzVWTlS1H/wUqUjEl7HNxdgAd1imhgjDpIVVZO1zzSV6oabEAYlZbcHA/Bhz+rqoAqLcCraE0LGsDJTKQ4eMApVS8lC8dvWr/hn2ShhChfNYTeeVCiXD0qv1RloasiaxlwR30YwL1HHhqaUwc/Z/H5bvZ6tEdDqbmcjoYj7A9mNnL1cAePyxXK3dmDs2Hf8EmWay+31njVsE6JF7MEx6IOw8qTjwIiIfbJeuZMSuK1iDkPqEwK86NzcE/V2OOXutk8FUlDmDXsc+GE/ODbZkDd2Rag/EETQfTycgeuLY1XE3Gy0fbtWvY7cuwW6ZhWRV4+16QEAM1ilgVEaqPQpCg22OEUUTCSMp/BBb/AQAA//8DAFBLAwQUAAYACAAAACEAMIkjd4YBAABIHwAAJwAAAHhsL3ByaW50ZXJTZXR0aW5ncy9wcmludGVyU2V0dGluZ3MxLmJpbuyYzU7CQBDH/ytVIBzQFzDGu4nBcvFG0CcwRhJOJuVAbDQhHDjWN+DMi3nxKXwCZ7u0y0LpAksgG2ZbsrPzsbvzg5ZpexhghC9McIM36kf4QJd0nxiTPCDtA1p0tFHcRIDgF/F18+dbCNQxa4S1CAJV9M4AOlGhUQdhcbiTVlC0XGFde3nuPq2zuevl6rqpkanTVpZOl0D9dFPnzC0ELi32Xc1+3IcmuKMEO/Q/M8Q74l2TncepnJMkofHUDwCOGXO4lUBg9dAOr2nRM6TCJ6bCJ9KGI0n3eIT5KdtI9otf3XdmKYsut8lSThaB5lEes2zd5ptYjj3E2LVEdad8iCw9WKOZ7VFEdBEKeSHmZ2G9n5LP8dNTiJazqSy9kE35aMkSs5G5spHXfGXDt0ojqhzNTo7DmnzEmjUWvM8vglStUpDG/u3flcaw4MoiE2ACTIAJMAEmwASYABPYB4G85N7HZDyHjwRWXzz4mAXv+bgEhHqB67oJvh+5EuT4rQj8AwAA//8DAFBLAwQUAAYACAAAACEAQ9DZqLEAAAArAQAAEAAAAHhsL2NhbGNDaGFpbi54bWxMz00KwjAQBeC94B3C7G3SVmuVpgUVT6AHCOnYFvJTkiB6e4Og6e6bN/CYabqXVuSJzk/WcMgzBgSNtP1kBg7323VTA/FBmF4oa5DDGz107XrVSKHkeRSTIbHBeA5jCPORUi9H1MJndkYTNw/rtAhxdAP1s0PR+xExaEULxiqqYwG0jSSOw6kEMsUbgP6CbeIusUrcJ9aJh8ScLbxozotFXian+PIl/b/ZfgAAAP//AwBQSwMEFAAGAAgAAAAhADzs9qZNAQAAYgIAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHySXU+DMBSG7038D6T30MJgagMsfmRXLjFxRuNd055tjbSQtsr27y2wIYvGy/a85+lzTpov9qoKvsBYWesCxRFBAWheC6m3BXpZL8NrFFjHtGBVraFAB7BoUV5e5LyhvDbwZOoGjJNgA0/SlvKmQDvnGoqx5TtQzEY+oX1xUxvFnD+aLW4Y/2BbwAkhc6zAMcEcwx0wbEYiOiIFH5HNp6l6gOAYKlCgncVxFOOfrAOj7J8NfWWSVNIdGj/TUXfKFnwojum9lWOwbduonfUa3j/Gb6vH537UUOpuVxxQmQtOuQHmalMyDibHk4tueRWzbuX3vJEg7g7lrVBSS+tM15Hj3wEP7P0HKojAG9HB/1R5nd0/rJeoTEiShiQNk2xNrmia0SR9794/6+8Mhwt1tPifOA/JTUh6YkZoNpsQT4Cy9z7/FeU3AAAA//8DAFBLAwQUAAYACAAAACEALAHhK8ABAADoAwAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcU8tu2zAQvBfIPwi8x1SctCgMikFgt0iBPozYSc8MtbKIUKRArgW7X19SjG0pSQu0Oi13FsPZ4Yhd7xqddeC8sqYgF5OcZGCkLZXZFOR+/fn8I8k8ClMKbQ0UZA+eXPOzd2zpbAsOFfgsUBhfkBqxnVHqZQ2N8JMAm4BU1jUCw9FtqK0qJWFh5bYBg3Sa5x8o7BBMCeV5eyQkiXHW4f+SllZGff5hvW+DYM5u2lYrKTBsyb8p6ay3FWafdhI0o0OQBXUrkFuncM9zRodHtpJCwzwQ80poD4yeGuwWRDRtKZTznHU460CidZlXv4JtVyR7FB6inIJ0wilhMMiKY+nQ17r16PhP6558DYCe0TCQmn05nB3W6opf9gOh+Otg4vouGiizO2E28C9XTN++ImpMu4a7xy6sFWrwP6qlcPiGKe+HpvTSkiVJ5U0Il9SwABRKj3QeTVltH5cK5HiLI/rFpOyFN++VPxt5xOd2a9Dt57b8A8HzQLRrSDBa+MWKX5V58vft2i4EwiEl4yZb1cJBGYJ1wE8NdhsC4nQkmdfxfcrDzGsgZvoh/bj8YjrJw9dH+dBj9PSL8t8AAAD//wMAUEsBAi0AFAAGAAgAAAAhAN/Pmy6SAQAAlAYAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAtVUwI/UAAABMAgAACwAAAAAAAAAAAAAAAACfAwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEA9PUHOxsBAABZBAAAGgAAAAAAAAAAAAAAAACLBgAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAYACAAAACEAPNWmZJwCAADbBQAADwAAAAAAAAAAAAAAAADmCAAAeGwvd29ya2Jvb2sueG1sUEsBAi0AFAAGAAgAAAAhAAr/F5p5BwAAzyAAABMAAAAAAAAAAAAAAAAArwsAAHhsL3RoZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEAO20yS8EAAABCAQAAIwAAAAAAAAAAAAAAAABZEwAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDIueG1sLnJlbHNQSwECLQAUAAYACAAAACEA3accpq8HAADGIAAAGAAAAAAAAAAAAAAAAABbFAAAeGwvd29ya3NoZWV0cy9zaGVldDIueG1sUEsBAi0AFAAGAAgAAAAhAPSgU2utEwAAomwAABgAAAAAAAAAAAAAAAAAQBwAAHhsL3dvcmtzaGVldHMvc2hlZXQzLnhtbFBLAQItABQABgAIAAAAIQCzhVqMwg4AAABEAAAYAAAAAAAAAAAAAAAAACMwAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAYACAAAACEAV7l3CYkOAADfOQAAFAAAAAAAAAAAAAAAAAAbPwAAeGwvc2hhcmVkU3RyaW5ncy54bWxQSwECLQAUAAYACAAAACEAH78iYZsEAABXGAAADQAAAAAAAAAAAAAAAADWTQAAeGwvc3R5bGVzLnhtbFBLAQItABQABgAIAAAAIQAwiSN3hgEAAEgfAAAnAAAAAAAAAAAAAAAAAJxSAAB4bC9wcmludGVyU2V0dGluZ3MvcHJpbnRlclNldHRpbmdzMS5iaW5QSwECLQAUAAYACAAAACEAQ9DZqLEAAAArAQAAEAAAAAAAAAAAAAAAAABnVAAAeGwvY2FsY0NoYWluLnhtbFBLAQItABQABgAIAAAAIQA87PamTQEAAGICAAARAAAAAAAAAAAAAAAAAEZVAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQAsAeErwAEAAOgDAAAQAAAAAAAAAAAAAAAAAMpXAABkb2NQcm9wcy9hcHAueG1sUEsFBgAAAAAPAA8A8AMAAMBaAAAAAA==";

// Download Excel Sheet using template XML modification (Preserves 100% Data Validation dropdowns, formulas & styles)
async function downloadExcelSheet() {
    if (typeof JSZip === 'undefined') {
        alert('JSZip library is loading. Please try again in a moment.');
        return;
    }

    try {
        // 1. Gather form values
        const senderName = document.getElementById('intSenderName').value.trim() || 'SHREEJA DIVINE PRODUCTS';
        const senderSub = document.getElementById('intSenderSub').value.trim() || 'Solanki Vishalbhai Arvindbhai';
        const senderAddressRaw = document.getElementById('intSenderAddress').value.trim();
        const senderPhone = document.getElementById('intSenderPhone').value.trim() || '+91-7878447897';

        const recipientName = document.getElementById('intRecipientName').value.trim() || 'Beth Walker';
        const recipientAddressRaw = document.getElementById('intRecipientAddress').value.trim();
        const recipientMobile = document.getElementById('intRecipientMobile').value.trim() || '13234964386';
        const recipientEmail = document.getElementById('intRecipientEmail').value.trim() || '';

        const prodDesc = document.getElementById('intProdDesc').value.trim() || 'wooden handicraft';
        const prodQty = parseFloat(document.getElementById('intProdQty').value.trim()) || 1;
        const prodUnit = document.getElementById('intProdUnit').value.trim() || '1350';
        const prodTotal = parseFloat(document.getElementById('intProdTotal').value.trim()) || 1350;

        const weightVal = parseFloat(document.getElementById('intWeight').value.trim()) || 280;
        const iossVal = document.getElementById('intIoss').value.trim() || '';
        const vatMsgVal = document.getElementById('intVatMsg').value.trim() || '';
        const orderNo = document.getElementById('intOrderNo').value.trim() || '1234';
        const barcodeVal = document.getElementById('intBarcodeValue').value.trim() || 'LP255987561IN';

        // 2. Parse Recipient Address
        const recAddressLines = recipientAddressRaw.split('\n').map(l => l.trim()).filter(l => l);
        let recAddLine1 = recAddressLines[0] || '';
        let recAddLine2 = recAddressLines[1] || '';
        let recAddLine3 = recAddressLines.slice(2).join(', ') || '';

        let recCity = 'BIRMINGHAM';
        let recState = 'ALABAMA';
        let recZip = '35205-5061';
        let destCountryName = 'United States of America';

        if (recAddressLines.length >= 3) {
            const lastLine = recAddressLines[recAddressLines.length - 1];
            const parts = lastLine.split(',');
            if (parts.length >= 2) {
                recCity = parts[0].trim();
                const stateZip = parts[1].trim().split(' ');
                recState = stateZip[0] || recState;
                if (stateZip.length > 1) recZip = stateZip.slice(1).join(' ');
            }
        }

        // Parse Sender Address
        const senderLines = senderAddressRaw.split('\n').map(l => l.trim()).filter(l => l);
        const senderLine1 = senderLines[0] || '459 Riddhi Siddhi Residency';
        const senderLine2 = senderLines[1] || 'Near ABC Mall, Canal Road';
        const senderLine3 = senderLines[2] || 'Kamrej, Surat - 394180';

        // 3. Load Template ZIP using JSZip
        const zip = await JSZip.loadAsync(INDIA_POST_TEMPLATE_BASE64, { base64: true });
        let sheet1Xml = await zip.file('xl/worksheets/sheet1.xml').async('text');
        let sheet2Xml = await zip.file('xl/worksheets/sheet2.xml').async('text');

        function escapeXml(str) {
            if (str === null || str === undefined) return '';
            return String(str)
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&apos;');
        }

        function setXmlCell(xmlStr, cellRef, val) {
            const pattern = new RegExp(`<c r="${cellRef}"(?:\\s+[^/>]*)?(?:/>|>(?:.*?)</c>)`, 's');
            const match = xmlStr.match(pattern);

            if (!match) return xmlStr;

            const fullMatch = match[0];
            const sMatch = fullMatch.match(/\s+s="([^"]*)"/);
            const sAttr = sMatch ? ` s="${sMatch[1]}"` : '';

            function escapeXml(s) {
                if (s === null || s === undefined) return '';
                return String(s)
                    .replace(/&/g, '&amp;')
                    .replace(/</g, '&lt;')
                    .replace(/>/g, '&gt;')
                    .replace(/"/g, '&quot;')
                    .replace(/'/g, '&apos;');
            }

            let newCell = '';
            if (val === null || val === undefined || val === '') {
                newCell = `<c r="${cellRef}"${sAttr}/>`;
            } else if (typeof val === 'number') {
                newCell = `<c r="${cellRef}"${sAttr}><v>${val}</v></c>`;
            } else {
                newCell = `<c r="${cellRef}"${sAttr} t="inlineStr"><is><t>${escapeXml(val)}</t></is></c>`;
            }

            return xmlStr.substring(0, match.index) + newCell + xmlStr.substring(match.index + fullMatch.length);
        }

        // 4. Update ArticleDetails (sheet1.xml)
        sheet1Xml = setXmlCell(sheet1Xml, 'C2', destCountryName);
        sheet1Xml = setXmlCell(sheet1Xml, 'G2', weightVal);
        sheet1Xml = setXmlCell(sheet1Xml, 'H2', prodTotal);
        sheet1Xml = setXmlCell(sheet1Xml, 'K2', senderSub);
        sheet1Xml = setXmlCell(sheet1Xml, 'L2', senderName);
        sheet1Xml = setXmlCell(sheet1Xml, 'M2', senderLine1);
        sheet1Xml = setXmlCell(sheet1Xml, 'N2', senderLine2);
        sheet1Xml = setXmlCell(sheet1Xml, 'O2', senderLine3);
        sheet1Xml = setXmlCell(sheet1Xml, 'X2', iossVal);
        sheet1Xml = setXmlCell(sheet1Xml, 'Y2', recipientName);
        sheet1Xml = setXmlCell(sheet1Xml, 'AA2', recAddLine1);
        sheet1Xml = setXmlCell(sheet1Xml, 'AB2', recAddLine2);
        sheet1Xml = setXmlCell(sheet1Xml, 'AC2', recAddLine3);
        sheet1Xml = setXmlCell(sheet1Xml, 'AD2', recCity);
        sheet1Xml = setXmlCell(sheet1Xml, 'AE2', recState);
        sheet1Xml = setXmlCell(sheet1Xml, 'AF2', recZip);
        sheet1Xml = setXmlCell(sheet1Xml, 'AG2', recipientEmail);
        sheet1Xml = setXmlCell(sheet1Xml, 'AH2', recipientMobile);
        sheet1Xml = setXmlCell(sheet1Xml, 'AI2', vatMsgVal);
        sheet1Xml = setXmlCell(sheet1Xml, 'AK2', barcodeVal);
        sheet1Xml = setXmlCell(sheet1Xml, 'AL2', senderPhone);
        sheet1Xml = setXmlCell(sheet1Xml, 'AM2', recipientMobile);
        sheet1Xml = setXmlCell(sheet1Xml, 'AS2', orderNo);

        // Clear Row 3 draft entry in sheet1.xml
        sheet1Xml = setXmlCell(sheet1Xml, 'C3', '');
        sheet1Xml = setXmlCell(sheet1Xml, 'B3', '');

        // 5. Update SubPieces (sheet2.xml)
        sheet2Xml = setXmlCell(sheet2Xml, 'C2', prodDesc);
        sheet2Xml = setXmlCell(sheet2Xml, 'F2', weightVal > 280 ? weightVal + 100 : 400);
        sheet2Xml = setXmlCell(sheet2Xml, 'G2', weightVal);
        sheet2Xml = setXmlCell(sheet2Xml, 'H2', prodTotal);

        // Save updated XML back to ZIP
        zip.file('xl/worksheets/sheet1.xml', sheet1Xml);
        zip.file('xl/worksheets/sheet2.xml', sheet2Xml);

        // 6. Generate Blob and Download
        const blob = await zip.generateAsync({
            type: 'blob',
            mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        });

        const fileName = `India_Post_BulkUpload_${barcodeVal || orderNo || 'Export'}.xlsx`;
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = fileName;
        link.click();
        URL.revokeObjectURL(link.href);

    } catch (err) {
        console.error('Failed to generate Excel sheet:', err);
        alert('Error generating Excel sheet: ' + err.message);
    }
}
